### ISSUE TITLE
League "Runs" Dates

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#11]
Please make the dates in the league descriptions page MM/DD/YYYY ? They are currently backwards and not consistent in each description. Some are YYYY/DD/MM and some are YYYY/MM/DD

**Comment by gary-dalton** [comment]
The admin interface for leagues is not written yet. These will eventually be admin editable.

Currently all dates are formatted the same and in proper ISO format. See below. If you really, really want them the other way, I will output format them to be Jun-07-2023 or 07-Jun-2023 format but not 06-07-2023 or 07-06-2023. Internally they will be stored as now.

[
                    'league_name' => "Team Bowl",
                    'league_description' => "This Monday night league is new in 2023. Each team rosters four or more players. Teams play a round robin cycle in one of two pools based on skills level. When the round robin cycle is completed after 3-4 weeks, one team is promoted and one team is relegated within each pool and a fresh round robin cycle begins. Standings are maintained. Members may play as many cycles as they wish.",
                    'term_start' => date('2023-05-29'),
                    'term_end' => date('2023-10-02'),
                    'capacity' => 64
                ],

                [
                    'league_name' => "Odd Couples",
                    'league_description' => "This Tuesday night league is designed to give members an opportunity to play with varying members and skill levels each week. A pairs game will be played between two teams of two players each. Teams are drawn randomly from those in attendance matching an experienced and a novice player together for each team. Individual points are accumulated and winners awarded in a variety of categories.",
                    'term_start' => date('2023-05-30'),
                    'term_end' => date('2023-10-03'),
                    'capacity' => 64
                ],

                [
                    'league_name' => "Wild Card Wednesdays",
                    'league_description' => "This Wednesday Night league is a competitive, multi-discipline league that offers variable game formats (singles, pairs, triples, fours, cutthroat) based on varying skill levels of attending members each week. Individual points are accumulated and winners awarded in a variety of categories.",
                    'term_start' => date('2023-05-31'),
                    'term_end' => date('2023-10-04'),
                    'capacity' => 64
                ],

                [
                    'league_name' => "Open Bowl",
                    'league_description' => "This Thursday afternoon league is an Open Bowl opportunity. Pairs or Triples teams are determined randomly based on attendance. Standings and points are not kept.",
                    'term_start' => date('2023-06-01'),
                    'term_end' => date('2023-10-05'),
                    'capacity' => 64
                ],

                [
                    'league_name' => "Social Bowl",
                    'league_description' => "This Thursday night social league is composed of static teams of 8 members. Each team may roster up to 8 players but only 4 players will compete each night in a fours format. Teams must consist of at least 1 male and 1 female player. A maximum of 14 teams can be accommodated this season.",
                    'term_start' => date('2023-06-01'),
                    'term_end' => date('2023-08-31'),
                    'capacity' => 84
                ],

**Comment by RekordMeister** [comment]
OK on admin interface for leagues. Immediately it is not an issue. For the average member the output format you suggest of Jun-07-2023 is more readable.

**Comment by gary-dalton** [comment]
Been thinking about this a little bit. I will move to a full localization date-time system. That means it will likely display on your computer the way you want it to. It will take me a little time to refactor all of the date time entries. Updates on this thread.

**Comment by gary-dalton** [comment]
Closed with Commit and Merge on 2023-03-03
