### ISSUE TITLE
Volunteer Form Submission

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#15]
![Volunteer 550 Server Error](https://user-images.githubusercontent.com/125783941/221935398-39590b19-48bd-4d7e-82ba-4373b8a75ce2.PNG)

"Error 500" screen post clicking submit on Volunteer form at 11:40ish. Refreshing browser shows selected volunteer tasks are saved for The Jesus. 

I have mentioned this to Board Members in case they encounter it.

**Comment by gary-dalton** [comment]
Not sure what I can do unless it is reproduced. I'll monitor it and test it a little.

**Comment by gary-dalton** [comment]
Nothing more happening here.
