### ISSUE TITLE
New Member Selection Wording

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#16]
FYI: Once the Social League Members must become New Club Members proposal passes on Wed Night... the wording if 2023 is entered in the member form must be changed...

"A portion of the membership fee is paid to Bowls USA and the Central Division" This sentence comes out entirely ONLY for the new member selection in the form. But remains in for returning members. 

Proposal dictates new members wont pay this in the first year.

**Comment by gary-dalton** [comment]
Is this applicable to ALL new members or only those from Social League. If all then easy to do.

**Comment by gary-dalton** [comment]
Closed with Commit and Merge on 2023-03-03
