### ISSUE TITLE
Volunteer Form Additions

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#22]
Top of Form: New Intro: 

"In order to complete your membership application you must submit the club volunteer form. Please indicate how you would like to volunteer with our club. It is an expectation that every member will help in some manner."

Please add a check box under House Committee for "Hospitality and Food Preparation for Club Events and Tournaments"

Please add a check box at the very bottom in no committee: "Call me to discuss volunteer options"

**Comment by gary-dalton** [comment]
I will add the check box near the top. It is unnoticeable  when near the bottom.
