### ISSUE TITLE
Group Events

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#23]
Delete: "Additional tables/chairs needed?" and Replace with: 

"Our club has 3 picnic tables and approximately 15 clubhouse chairs available which can be moved outside. If you would like additional tables or chairs please indicate your need. Please indicate if you plan to supply your own."

**Comment by gary-dalton** [comment]
That is a lot of words for a form

**Comment by gary-dalton** [comment]
I added a information popup. Please verify the language used. @RekordMeister 

"Our club has 3 picnic tables and approximately 15 clubhouse chairs available which can be moved outside. If you think you might need more, please discuss this with your Group Event Coordinator."

**Comment by RekordMeister** [comment]
Agreed with too much wording for a form. Popup and text sound good. Dale might propose something else once he gets into it.

**Comment by gary-dalton** [comment]
Closing this for now. We can reopen if need be.

I think the rollover help works well. I might use this other places as well.
