### ISSUE TITLE
Volunteer interest optional

### ISSUE THREAD

**Issue by gary-dalton** [gary-dalton/bowlsmke-issues#25]
Add a checkbox to turn of the requirement for volunteer interest. For Membership director

**Comment by gary-dalton** [comment]
@RekordMeister
Is this something that resets every year or does it stick until changed?

It would be in the admin section for the membership director. I can also set a few by hand once they are entered but they would already receive the welcome notice and be encouraged to volunteer but no reminders.

**Comment by RekordMeister** [comment]
Audience Applicable to: 
-Honorary Members (always sticks) 
-Associate Members (only if they would renew again, would it stick) but they should not see the Volunteer Form at all. 
-Members with Physical Limitations (here you have two cases... 1) those that are older or have a physical concern and really can't volunteer with most tasks, but could help with house or cooking or something easy and 2) the case where a normally physically active person is temporarily injured and can't mow the greens with a broken leg

I think Mark implied there are certain older members who have never volunteered and likely simply wont so as you suggest the Membership Director just needs to be able to toggle the requirement for volunteering from some individuals. 

Trying to instill a volunteer culture shift the last couple years and trying to win that concept back which is improving. 

Keep in mind Barb is Membership Director. But Mark is going to deal with the volunteers this season. So depending where you put the permissions, one may need to communicate, make requests from the other.

**Comment by gary-dalton** [comment]
Right now, the reminders only go to Returning Members.

I think I'll make the toggle stick, therefore; it is part of the member profile and not the volunteer interest. (this is what I needed to know)

I can easily tweak permissions.

**Comment by gary-dalton** [comment]
Closed with #89
