### ISSUE TITLE
Membership Creation

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#43]
While creating the Bunny Profile Membership this morning...

I failed to checkbox any league stuff, proceeded to paypal, logged in with my patpal, and then tried to back browser out of paypal back to the membership form (mid payment process).... and could not get there...
 
...and I can't seem to access Bunny's League page to complete the membership...

went back thru the Dashboard, also did not get me there...

Log in and Log out of Bunny profile did not solve it.

I'll work through that same paypal behavior on a new profile.... again tonite and see what happens ..

**Comment by gary-dalton** [comment]
Are you sure Bunny is a nihilist?

Membership is completed upon submission from membership page but payment is not completed. The browser back button should not work for this. It would be better to not have the membership completed until success return. Once your membership is completed, there is no editing of it permitted. Nor does one need a different membership. The same result if you click complete on zelle or check, i.e. that transaction is considered complete but the payment is pending.

This is tricky interaction, that I can solve by not completing the membership until after return to paypal payment success. But then there are a lot of branching nodes. This is what I will do and cover the branches.

**Comment by gary-dalton** [comment]
Overall, in the DB I have all the records of the transaction. Problem is no notifications went out because of the paypal did not complete, either success or fail just nothing. That is a chicken/egg problem. Perhaps solved by the previous comment. 

$payByPaypal = new \App\Actions\Ggis\PayByPaypal;
$payByPaypal->execute($payment, $this->type, 'ProcessNewMember');

**Comment by gary-dalton** [comment]
This will be solved by implementing a cart. I had hoped to delay the cart until after site was live.

**Comment by RekordMeister** [comment]
I see. Definite no man's land. User could certainly try to back up like i did and end up frustrated. However, if we can get by with returning members, you could delay the cart for a bit...
