### ISSUE TITLE
Paypal Selection...

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#44]
Barb: 
"For PayPal payment it took me to PayPal and there is an option to pay in 4 installments. I hope we can disable that option as it will cost us even more in fees and require more tracking by me and the membership chair."

I'm thinking this is a selection in her personal paypal...

or do we have to do something on our side? 

I doubt people would select that option on their side...

**Comment by gary-dalton** [comment]
I have little to no control over what happens on the paypal account side of things. I'll test it and see what happens but thinking that we do not incur further charges because we are not allowing 4 payments but payable NOW.

**Comment by RekordMeister** [comment]
OK, so we are only allowing payable NOW... on our end, right?

**Comment by gary-dalton** [comment]
It is not an option, we are not doing subscriptions or invoices. So, CORRECT.

**Comment by gary-dalton** [comment]
I tested this pay in 4 option. It becomes a loan to fakejanedoe. We do not see anything different on our (the merchant) end. Closing this issue.
