### ISSUE TITLE
Volunteer Form Check Boxes

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#45]
We need to split/sub divide the days into additional checkboxes on the following... 
I've corrected this in the Volunteer.doc already

GAMES COMMITTEE
League Directors or Co-Directors Tue 7pm to 9pm
League Directors or Co-Directors Wed 7pm to 9pm
League Directors or Co-Directors Thur 1pm to 3pm

MEMBERSHIP COMMITTEE
Coach New Member Lessons (Tue 6pm to 7pm, will receive training)
Coach New Member Lessons (Wed 6pm to 7pm, will receive training)

HOUSE COMMITTEE
in the header sentences... "Accurately inventories product", not produce.

**Comment by gary-dalton** [comment]
Do you need League Director for Monday eve?
