### ISSUE TITLE
VOLUNTEER FORM

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#5]
Latin Placeholders appearing ONLY in the Games Committee section under each listed task

**Comment by gary-dalton** [comment]
This is intentional! I want admin users to figure out how and where to change these. It will be removed before going Live.

**Comment by gary-dalton** [comment]
Planned until site is live.

**Comment by RekordMeister** [comment]
I guess, I don't understand, but I will warn the team so they don't all mention it.
