### ISSUE TITLE
Payment completion texts

### ISSUE THREAD

**Issue by gary-dalton** [gary-dalton/bowlsmke-issues#53]
We have two payment types: digital and manual. We also currently have two different purchase types: membership and groupevent.

Each of these permutations needs to have its own termination message for completing purchase. This concept will be part of the cart integration.

Build two payment endpoints, manual-payment-saved and digital-payment-completed. In each of these modularly combine markdown messages that are suitable for each permutation.

**Comment by gary-dalton** [comment]
@RekordMeister

So hopefully this is understandable to you. Each of the below messages is a modular piece of a message. The final permutation message is that which pull the pieces that match the correct case.

## Payment Saved

Your payment has been saved but is not complete. Please complete your payment using your chosen method. Once your payment has been received and processed, you will receive email notification. We hope to receive your payment and have it completely processed within 10 days.

## Payment Completed

Your payment has been successfully processed electronically and is completed.

## Welcome New Member

We are thrilled to welcome you as a new member of the Milwaukee Lawn Bowling Club! As a community of lawn bowling enthusiasts, we are dedicated to promoting the sport and providing a friendly and supportive environment for all of our members.

We encourage you to take advantage of all that the club has to offer. If you have any questions or would like more information about our club, please do not hesitate to contact admin@milwaukeelawnbowls.com

We look forward to seeing you on the greens and getting to know you better. Welcome to the Milwaukee Lawn Bowling Club!

## Volunteering

As a next step, complete your [**Volunteer Interest**]( /volunteer).

As a reminder, we expect all members to contribute and get involved in the club in some capacity, whether it be through volunteering for events, leading a committee, or assisting with various tasks. The [Volunteer Interest Form]( /volunteer ) is an opportunity for you to let us know what areas you're interested in getting involved with, so that we can match you with opportunities that align with your interests and skills.

## Transaction Details

You should be receiving an email from us detailing your transaction with us. It will be from system@milwaukeelawnbowls.com. If you do not receive this email from us, please first check your spam folder and then reach out to us either via the contact form or at admin@milwaukeelawnbowls.com.

## Dashboard

Every time you log in, the place to start is the dashboard. From here you will be able to access all parts of the application and easily review your notifications. We are in the very early stages of development, so expect new areas to open regularly. If you are interested, view our [aspirational roadmap](/aspiration).

## Welcome Group Event

On behalf of our lawn bowling club, I would like to extend a warm welcome to you. We look forward to having you join us on the greens.

As a reminder, all group event registrations must be coordinated with our Group Events Coordinator to ensure availability of the greens and any necessary equipment. Please reach out to our Group Events Coordinator at groupevents@milwaukeelawnbowls.com to discuss your event.

The Group Events Coordinator will provide you with all the necessary details to ensure that your group has a successful and enjoyable experience.

If you have a balance due, please ensure to pay that at least seven days prior to the event.

## Group Event Balance Due Paid

Thank you for paying down the balance due in a timely manner.

Hopefully, you have been in contact with our Group Events Coordination to finalize the details of your event. We look forward to sharing the greens with you.

**Comment by gary-dalton** [comment]
An update

## Volunteering

As a next step, complete your [**Volunteer Interest**]( /volunteer).

If this is your first year with our club, you do not need to complete this form.

As a reminder, we expect all returning members to contribute and get involved in the club in some capacity, whether it be through volunteering for events, leading a committee, or assisting with various tasks. The [Volunteer Interest Form]( /volunteer ) is an opportunity for you to let us know what areas you're interested in getting involved with, so that we can match you with opportunities that align with your interests and skills.

**Comment by RekordMeister** [comment]
Claro. See Red Text on Transact and GE Balance paid…
