### ISSUE TITLE
Group Event policies and procedures

### ISSUE THREAD

**Issue by gary-dalton** [gary-dalton/bowlsmke-issues#55]
@RekordMeister

I realized I had not linked in the policies and procedures on the Group Event consent. Don't actually know which link to use.

Please pass the link to me and I will add it to the forms.

**Comment by gary-dalton** [comment]
Applies to lb/resources/views/livewire/group-wizard-02.blade.php 
and
lb/resources/views/livewire/group-event/guest/view.blade.php

**Comment by RekordMeister** [comment]
I’llfix the Group  Events Page and Policies this weekend.

From: Gary Dalton ***@***.***>
Sent: Friday, March 31, 2023 4:29 PM
To: gary-dalton/bowlsmke-issues ***@***.***>
Cc: scott lehmann ***@***.***>; Mention ***@***.***>
Subject: [gary-dalton/bowlsmke-issues] Group Event policies and procedures (Issue #55)


@RekordMeister<https://github.com/RekordMeister>

I realized I had not linked in the policies and procedures on the Group Event consent. Don't actually know which link to use.

Please pass the link to me and I will add it to the forms.
