### ISSUE TITLE
Edit Member

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#57]
Edit Member currently yields... not certain if you have that ready... same holds for delete member. 

{"id":19,"first_name":"Dude","email":"scottplehmann@gmail.com","email_verified_at":"2023-04-01T23:33:27.000000Z","two_factor_confirmed_at":null,"current_team_id":null,"profile_photo_path":"profile-photos\/vmYDDbOMpmqguaowFJPC2sLKi8l9Zk2c8UpCzqOl.jpg","created_at":"2023-04-01T23:32:09.000000Z","updated_at":"2023-04-01T23:35:06.000000Z","last_name":"Lebowski","deleted_at":null,"profile_photo_url":"https:\/\/app.milwaukeelawnbowls.com\/storage\/profile-photos\/vmYDDbOMpmqguaowFJPC2sLKi8l9Zk2c8UpCzqOl.jpg"}

**Comment by gary-dalton** [comment]
One should NEVER delete users, members, memberships, or payments. these exists as a group. Payments are NOT PERMITTED to be deleted only archived. This part of the interface is not yet fully built. 

Missing delete is not a bug. Ability to access is only available to root. Please ask me before doing this type of action.

Missing archive is incomplete functionality.

**Comment by RekordMeister** [comment]
I was trying to edit Kenneth Freund membership at the time. Clicking on his record yielded the funky output.

**Comment by gary-dalton** [comment]
Delete capability is removed. There is now edit functionality. It is also possible to archive users.
