### ISSUE TITLE
Add Group Event (Time)

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#6]
All Group Events are Two Hours. Don't need End Time. 

Selecting the Time was a little tricky. Is there an easier way?

**Comment by gary-dalton** [comment]
Good to know I don't need an end time. I will remove that. I agree the time selector is quirky, that is built-in the browser and I noticed does not even work in firefox.

Are there a limited number of possible start times? Like every hour or half hour between 10 am and 6pm? then I would make a pulldown that lists just those.

**Comment by RekordMeister** [comment]
I was debating the same point about limited times earlier and started to write it up and scratched it as we have had some odd timed events in the past, i.e. on the weekend or earlier in the day for global visitors.

Also, as we don't know te size of of our membership and hence whether we will require an additional green or create other random weekly open bowls etc...
it is therefore hard to build a limited time list at this point. Could be we have to later on in July or so...

I didn't get to tetsing firefox yet ;-) But will.

**Comment by gary-dalton** [comment]
Right now, I've got start times available from 10am to 6pm on every half hour. Does this seem correct or should it be changed? If changed, to what?
@RekordMeister

**Comment by RekordMeister** [comment]
This should be fine.
