### ISSUE TITLE
Submit Button on Group Events 

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#7]
Submit button yields a funky screen. No confirmation that Group Event is submitted for user to see.

**Comment by gary-dalton** [comment]
It is a funky screen. That is a debug screen. I can turn it off by setting the site to 'production' versus 'debug'. Would you like me to do that?

Working on the reported issue.

**Comment by RekordMeister** [comment]
Yes, one less item 6 others will remark about.

**Comment by RekordMeister** [comment]
odd timed events in the past, i.e. on the weekend or earlier in the day for global visitors. 

Also, as we don't know te size of of our membership and hence whether we will require an additional green or create other random weekly open bowls etc...
it is therefore hard to build a limited time list at this point. Could be we have to later on in July or so...

I didn't get to tetsing firefox yet ;-) But will.
