### ISSUE TITLE
Page Jumps

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#8]
In the forms... when clicking 'next step' to move to the next sections... i.e. in Group Events... the next section always drops the user into the mid-page area of the section, rather than at the top. Hence the user has to scroll up to start at the top each time.

**Comment by gary-dalton** [comment]
I think I have fixed this the way you might want it. I have set it so that it loads to the top of the progress bar. Let me know if this solves it the way you like.
@RekordMeister

**Comment by RekordMeister** [comment]
Yes, this seems better now. TY
