### ISSUE TITLE
Group Events "$" Amount Payed

### ISSUE THREAD

**Issue by RekordMeister** [gary-dalton/bowlsmke-issues#9]
If user enters symbol ($) 200/300/400 (not just the number) into the "Amount Being Paid Today" field in Group Events and clicks submit at the end it freaks out big. Need to update the field for only numbers allowed or make a notation for user, only input number amount. No chars.

**Comment by gary-dalton** [comment]
Thank you Scott, this is a real bug and will be fixed.
