### ISSUE TITLE
memberNoMembership should have a cutoff

### ISSUE THREAD

**Issue by gary-dalton** [gary-dalton/bowlsmke-issues#94]
Right now persons who have entered member information but have not completed a membership get a notification once a week. At a certain point, this is spam. I suggest we send a final notice to them at week four. You may review a list of these folks at

https://app.milwaukeelawnbowls.com/admin/users?tab=3&type=1

@RekordMeister

**Comment by RekordMeister** [comment]
Gary,

Agreed on the final notice at week 4. I don’t recognize names in the list link so most likely Social League members. There was a conversation tonight that it may be difficult for Team Captains in Social League to rally their normal 4-8 teammates to commit/register and that teams tend to come together last minute. Mark can check the list with Dawn too. For the month of May and first half of June every year, it may be best to send the reminder notification as there are always last minute registrations, but generally 4 notifications seems sufficient to me.

Scott

From: Gary Dalton ***@***.******@***.***>>
Sent: Monday, May 15, 2023 9:41 PM
To: gary-dalton/bowlsmke-issues ***@***.******@***.***>>
Cc: scott lehmann ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [gary-dalton/bowlsmke-issues] memberNoMembership should have a cutoff (Issue #94)


Right now persons who have entered member information but have not completed a membership get a notification once a week. At a certain point, this is spam. I suggest we send a final notice to them at week four. You may review a list of these folks at

https://app.milwaukeelawnbowls.com/admin/users?tab=3&type=1

@RekordMeister<https://github.com/RekordMeister>

**Comment by RekordMeister** [comment]
I’ve reached out to these people a couple of times myself via email and phone call.  I think that the system can stop the notifications now.

Mark

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: scott ***@***.***>
Sent: Monday, May 15, 2023 10:16 PM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>; Mark ***@***.***>
Subject: RE: [gary-dalton/bowlsmke-issues] memberNoMembership should have a cutoff (Issue #94)

Gary,

Agreed on the final notice at week 4. I don’t recognize names in the list link so most likely Social League members. There was a conversation tonight that it may be difficult for Team Captains in Social League to rally their normal 4-8 teammates to commit/register and that teams tend to come together last minute. Mark can check the list with Dawn too. For the month of May and first half of June every year, it may be best to send the reminder notification as there are always last minute registrations, but generally 4 notifications seems sufficient to me.

Scott

From: Gary Dalton ***@***.******@***.***>>
Sent: Monday, May 15, 2023 9:41 PM
To: gary-dalton/bowlsmke-issues ***@***.******@***.***>>
Cc: scott lehmann ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [gary-dalton/bowlsmke-issues] memberNoMembership should have a cutoff (Issue #94)


Right now persons who have entered member information but have not completed a membership get a notification once a week. At a certain point, this is spam. I suggest we send a final notice to them at week four. You may review a list of these folks at

https://app.milwaukeelawnbowls.com/admin/users?tab=3&type=1

@RekordMeister<https://github.com/RekordMeister>
